development:
  adapter: mysql2
  database: shouldigo_devel
  username: root
  password:
  
test:
  adapter: mysql2
  database: shouldigo_test
  username: root
  password: 
    
production:
      adapter: mysql2
      encoding: utf8
      database: shouldigo_production
      username: 
      password: 
